const = 
{
	["shapeNames"] = 
	{
		["Landmine"] = "landmine",
		["FARP CP Blindage"] = "kp_ug",
		["Subsidiary structure C"] = "saray-c",
		["Barracks 2"] = "kazarma2",
		["Small house 2C"] = "dom2c",
		["Military staff"] = "aviashtab",
		["Container 20ft"] = "container_20ft",
		["Tanker Elnya 160"] = "elnya",
		["Pipes big"] = "pipes_big_cargo",
		["Tech hangar A"] = "ceh_ang_a",
		["Oil derrick"] = "neftevyshka",
		["Tech combine"] = "kombinat",
		["Garage B"] = "garage_b",
		["Pilot standing"] = "pilot_parashut",
		["Airshow_Crowd"] = "Crowd1",
		["Airshow_Cone"] = "Comp_cone",
		["Hangar A"] = "angar_a",
		["Road outpost"] = "block-onroad",
		["Repair workshop"] = "tech",
		["Subsidiary structure D"] = "saray-d",
		["Outpost"] = "block",
		["FARP Ammo Dump Coating"] = "SetkaKP",
		["Small house 1C area"] = "dom2c-all",
		["Tank 2"] = "airbase_tbilisi_tank_01",
		["Boiler-house A"] = "kotelnaya_a",
		["Parachute"] = "parash",
		["Workshop A"] = "tec_a",
		["Downed pilot"] = "cadaver",
		["Small werehouse 1"] = "s1",
		["Bulk Cargo Ship Ivanov"] = "barge-1",
		["Fueltank"] = "fueltank_cargo",
		["Garage small B"] = "garagh-small-b",
		["Small werehouse 4"] = "s4",
		["Oiltank"] = "oiltank_cargo",
		["Container 40ft"] = "container_40ft",
		["Shop"] = "magazin",
		["Bunker 2"] = "dot2",
		["Subsidiary structure B"] = "saray-b",
		["FARP Fuel Depot"] = "gsm rus",
		["White_Flag"] = "H-Flag_W",
		["Coach cargo"] = "wagon-gruz",
		["Oil rig"] = "oil_platform",
		["Helipad Single"] = "farp",
		["Electric power box"] = "tr_budka",
		["Tank 3"] = "airbase_tbilisi_tank_02",
		["Red_Flag"] = "H-flag_R",
		["Gas platform"] = "gas_platform",
		["Container red 3"] = "konteiner_red3",
		["Garage A"] = "garage_a",
		["Hangar B"] = "angar_b",
		["Trunks small"] = "trunks_small_cargo",
		["Black_Tyre"] = "H-tyre_B",
		["Cafe"] = "stolovaya",
		["Restaurant 1"] = "restoran1",
		["Trunks long"] = "trunks_long_cargo",
		["Subsidiary structure A"] = "saray-a",
		["Tetrapod"] = "tetrapod_cargo",
		["Container white"] = "konteiner_white",
		["Warehouse"] = "sklad",
		["Tank"] = "bak",
		["Oil platform"] = "plavbaza",
		["Pipes small"] = "pipes_small_cargo",
		["Watch Tower Armed"] = "ohr-vyshka",
		["FARP Command Post"] = "kp-ug",
		["Railway crossing B"] = "pereezd_small",
		["Railway crossing A"] = "pereezd_big",
		["Subsidiary structure F"] = "saray-f",
		["Gate"] = "gate",
		["Farm A"] = "ferma_a",
		["FARP"] = "farps",
		["Small werehouse 3"] = "s3",
		["Passenger boat"] = "zwezdny",
		["Water tower A"] = "wodokachka_a",
		["F-shape barrier"] = "f_bar_cargo",
		["Railway station"] = "r_vok_sd",
		["Coach a tank blue"] = "wagon-cisterna_blue",
		["Bunker 1"] = "dot",
		["Tech Hangar A"] = "ceh_ang_a",
		["Supermarket A"] = "uniwersam_a",
		["Coach a platform"] = "wagon-platforma",
		["Garage small A"] = "garagh-small-a",
		["Container brown"] = "konteiner_brown",
		["TV tower"] = "tele_bash",
		["Bulk Cargo Ship Yakushev"] = "barge-2",
		["Pilot F15 Parachute"] = "pilot_f15_parachute",
		["Farm B"] = "ferma_b",
		["GeneratorF"] = "GeneratorF",
		["Passenger liner"] = "yastrebow",
		["Container red 2"] = "konteiner_red2",
		["Coach a passenger"] = "wagon-pass",
		["WC"] = "WC",
		["Black_Tyre_WF"] = "H-tyre_B_WF",
		["Electric locomotive"] = "elektrowoz",
		["Armed house"] = "home1_a",
		["Coach a tank yellow"] = "wagon-cisterna_yellow",
		["Subsidiary structure 2"] = "hozdomik2",
		[".Ammunition depot"] = "SkladC",
		["Small werehouse 2"] = "s2",
		["Windsock"] = "H-Windsock_RW",
		["Small house 1B"] = "domik1b",
		["Container camo"] = "bw_container_cargo",
		["Locomotive"] = "teplowoz",
		["Subsidiary structure 1"] = "hozdomik1",
		["Pump station"] = "nasos",
		["Small house 1B area"] = "domik1b-all",
		["Coach cargo open"] = "wagon-gruz-otkr",
		["Container red 1"] = "konteiner_red1",
		["Subsidiary structure G"] = "saray-g",
		["White_Tyre"] = "H-tyre_W",
		["FARP Tent"] = "PalatkaB",
		["Subsidiary structure 3"] = "hozdomik3",
		["Black_Tyre_RF"] = "H-tyre_B_RF",
		["Comms tower M"] = "tele_bash_m",
		[".Command Center"] = "ComCenter",
		["Fuel tank"] = "toplivo",
		["Cargo1"] = "ab-212_cargo",
		["Shelter B"] = "ukrytie_b",
		["Chemical tank A"] = "him_bak_a",
		["Shelter"] = "ukrytie",
		["Small house 1A area"] = "domik1a-all",
		["Subsidiary structure E"] = "saray-e",
		["Small house 1A"] = "domik1a",
	}, -- end of ["shapeNames"]
	["callsigns"] = 
	{
		["NATO"] = 
		{
			["AWACS"] = 
			{
				["Darkstar"] = 5,
				["Focus"] = 4,
				["Wizard"] = 3,
				["Magic"] = 2,
				["Overlord"] = 1,
			}, -- end of ["AWACS"]
			["rules"] = 
			{
				["groupLimit"] = 9,
			}, -- end of ["rules"]
			["aircraft"] = 
			{
				["Uzi"] = 3,
				["Pontiac"] = 8,
				["Chevy"] = 7,
				["Dodge"] = 5,
				["Ford"] = 6,
				["Enfield"] = 1,
				["Colt"] = 4,
				["Springfield"] = 2,
			}, -- end of ["aircraft"]
			["unique"] = 
			{
				["A10"] = 
				{
					["Boar"] = 10,
					["Pig"] = 11,
					["rules"] = 
					{
						["canUseAircraft"] = true,
						["appliesTo"] = 
						{
							[1] = "A-10C",
							[2] = "A-10A",
						}, -- end of ["appliesTo"]
					}, -- end of ["rules"]
					["Tusk"] = 12,
					["Hawg"] = 9,
				}, -- end of ["A10"]
			}, -- end of ["unique"]
			["JTAC"] = 
			{
				["Ferret"] = 10,
				["Finger"] = 8,
				["Deathstar"] = 15,
				["Pointer"] = 4,
				["Anvil"] = 16,
				["Darknight"] = 2,
				["Whiplash"] = 7,
				["Warrior"] = 3,
				["Eyeball"] = 5,
				["Mantis"] = 18,
				["Playboy"] = 12,
				["Axeman"] = 1,
				["Moonbeam"] = 6,
				["Hammer"] = 13,
				["Shaba"] = 11,
				["Badger"] = 19,
				["Jaguar"] = 14,
				["Firefly"] = 17,
				["Pinpoint"] = 9,
			}, -- end of ["JTAC"]
			["TANKER"] = 
			{
				["Texaco"] = 1,
				["Arco"] = 2,
				["Shell"] = 3,
			}, -- end of ["TANKER"]
		}, -- end of ["NATO"]
	}, -- end of ["callsigns"]
} -- end of const
